"""
Simulation interface for running AWS Palace workflows.

This module provides the :class:`Simulation` class, which executes Palace
simulations (locally or on HPC systems) and extracts outputs such as
capacitance matrices, eigenfrequencies, linewidths, and S-parameters.
"""


import pandas as pd
import subprocess
import matplotlib.pyplot as plt
import pyvista as pv
import numpy as np
import json
from .config import Config
from .tools import Tools

class Simulation:

    """
    Interface for running AWS Palace simulations and extracting results.

    This class manages the full simulation workflow, including:
    - executing Palace simulations locally or on HPC systems
    - handling job submission (e.g., Slurm)
    - extracting simulation outputs (capacitance matrices, eigenfrequencies, S-parameters, etc.)

    Parameters
    ----------
    config : pypalace.config.Config
        Config object defining the Palace simulation.
    path_to_palace : str
        Path to the Palace executable.
    """


    def __init__(self,config:Config,path_to_palace:str):
        
        """
        Initialize a Simulation object.

        Parameters
        ----------
        config : pypalace.config.Config
            Config object defining the Palace simulation.
        path_to_palace : str
            Path to the Palace executable.
        """
        
        self.path_to_palace = path_to_palace
        self.config = config
        self.path_to_json = self.config.config_name
        
    def HPC_options(partition,time,nodes,ntasks_per_node,mem,job_name,custom = None):
        
        """
        Define Slurm job directives for running simulations on an HPC system.

        The returned list can be passed to :meth:`Simulation.run` to submit
        the simulation via ``sbatch``.

        Parameters
        ----------
        partition : str
            Slurm partition name.
        time : str
            Job time limit (e.g., ``"02:00:00"``).
        nodes : int
            Number of nodes.
        ntasks_per_node : int
            Number of MPI tasks per node.
        mem : int
            Memory per node in GB.
        job_name : str
            Name of the Slurm job.
        custom : list, optional
            Additional Slurm directives.

        Returns
        -------
        list
            List of Slurm directive strings.
        """
        
        partition = "partition={}".format(partition)
        time = "time={}".format(time)
        nodes = "nodes={}".format(nodes)
        ntasks_per_node = "ntasks-per-node={}".format(ntasks_per_node)
        mem = "mem={}G".format(mem)
        job_name = "job-name={}".format(job_name)
        
        slurm_list = [partition,time,nodes,ntasks_per_node,mem,job_name]
        
        if custom != None:
            for sbatches in custom:
                slurm_list.append(sbatches)
        
        return slurm_list
    
        
    def run(self,n,HPC_options=None,custom_script_name=None):
    
        """
        Run the simulation.

        If ``HPC_options`` is provided, a Slurm job script is generated and
        submitted using ``sbatch``. Otherwise, the simulation is executed locally
        using ``mpirun``.

        Parameters
        ----------
        n : int
            Number of MPI processes.
        HPC_options : list, optional
            Slurm directive list generated by :meth:`Simulation.HPC_options`.
        custom_script_name : str, optional
            Name of the generated job script file.
        """
    
        if self.config.saved == False:
            self.config.save_config()
    
        if HPC_options == None:
            command = subprocess.run(["mpirun", "-n",str(n),self.path_to_palace,self.path_to_json],capture_output=True,text=True)
            print(command.stdout.strip())
            print(command.stderr.strip())

        else:
                if custom_script_name == None:
                    custom_script_name = "palace_jobscript.sh"
                
                with open(custom_script_name, "w") as file:
                
                    file.write("#!/bin/bash\n")
                    file.write("\n")
                    
                    for sbatches in HPC_options:
                        file.write("#SBATCH --{}\n".format(sbatches))
                
                    file.write("\n")
                    
                    file.write('export PALACE="{}"\n'.format(self.path_to_palace))
                    file.write('export MY_SIM="{}"\n'.format(self.path_to_json))
                    file.write('export MPI_PROCESSES={}\n'.format(n))
                    file.write("\n")
                    file.write("mpirun -n $MPI_PROCESSES $PALACE $MY_SIM")
                    

                command = subprocess.run(['sbatch', custom_script_name],capture_output=True,text=True)
                print(command.stdout.strip())
                print(command.stderr.strip())
                
                
    def get_capacitance_matrix(self):
    
        """
        Extract the capacitance matrix from an electrostatic simulation.

        Returns
        -------
        pandas.DataFrame
            Capacitance matrix labeled by terminal names.

        Raises
        ------
        ValueError
            If the simulation type is not electrostatic.
        """
        
        if self.config.config["Problem"]["Type"] != "Electrostatic":
            raise ValueError("Simulation type is not electrostatic, no capacitance matrix to extract")
        else:
            cap_matrix_results = self.config.config["Problem"]["Output"]+"/terminal-C.csv"
            cap_matrix = pd.read_csv(cap_matrix_results)
            cap_matrix = cap_matrix.drop(columns=['        i'])
            
            meshfile = self.config.config["Model"]["Mesh"]
            mesh_attributes = Tools.get_mesh_attributes(meshfile)
            
            setup = self.config.config["Boundaries"]["Terminal"]
            names = []
            for terminal in setup:
                cap_matrix_index = terminal["Index"]
                ID = terminal["Attributes"][0]
                names.append(mesh_attributes[mesh_attributes.ID==str(ID)].Name.iloc[0])
            
            cap_matrix.index = names
            cap_matrix.columns = names
            
            return cap_matrix
    
    def get_frequency_eigenmode(self, mode: int):
        """
        Extract the eigenfrequency of a specified mode.

        Parameters
        ----------
        mode : int
            Eigenmode index.

        Returns
        -------
        float
            Eigenfrequency in GHz.

        Raises
        ------
        ValueError
            If the simulation type is not eigenmode.
        """
        
        if self.config.config["Problem"]["Type"] != "Eigenmode":
            raise ValueError("Simulation type is not eigenmode, no eigenfrequency to extract")
            
        else:
        
            freq_results = self.config.config["Problem"]["Output"]+"/eig.csv"
            freqs = pd.read_csv(freq_results,usecols = [0,1,2,3])
            freqs.columns = ["m","frequency_GHz","frequency_Im","Q"]
            f_i = freqs[freqs.m == mode].frequency_GHz.iloc[0]
            
            return f_i
            
            
    def get_kappa_eigenmode(self,mode:int):
        """
        Compute the linewidth (kappa) of a specified eigenmode.

        Parameters
        ----------
        mode : int
            Eigenmode index.

        Returns
        -------
        float
            Linewidth (kappa) in GHz.

        Raises
        ------
        ValueError
            If the simulation type is not eigenmode.
        """
        
        if self.config.config["Problem"]["Type"] != "Eigenmode":
            raise ValueError("Simulation type is not eigenmode, no k_int to extract")
            
        else:
        
            freq_results = self.config.config["Problem"]["Output"]+"/eig.csv"
            freqs = pd.read_csv(freq_results,usecols = [0,1,2,3])
            freqs.columns = ["m","frequency_GHz","frequency_Im","Q"]
            f_i = freqs[freqs.m == mode].frequency_GHz.iloc[0]
            Q_i = freqs[freqs.m == mode].Q.iloc[0]
            
            kappa_i_int = f_i/Q_i
            
            return kappa_i_int
                
    def get_portEPR(self,port_index:int,mode:int):
        """
        Extract the energy participation ratio (EPR) for a given port and mode.

        Parameters
        ----------
        port_index : int
            Port index.
        mode : int
            Eigenmode index.

        Returns
        -------
        float
            Energy participation ratio.

        Raises
        ------
        ValueError
            If the simulation type is not eigenmode or if the port is not defined.
        """
    
        if self.config.config["Problem"]["Type"] != "Eigenmode":
            raise ValueError("Simulation type is not eigenmode, no port EPR to extract")
            
        try:
            EPR_results = self.config.config["Problem"]["Output"]+"/port-EPR.csv"
            EPR = pd.read_csv(EPR_results,usecols=[0,port_index])
            EPR.columns = ["m","EPR"]
            p_i = EPR[EPR.m == mode].EPR.iloc[0]
            return p_i
            
        except:
            raise ValueError("Are you sure you defined a port?")

    def get_Sij(self, index1: int, index2: int):
        """
        Extract S-parameters between two ports from a driven simulation.

        Parameters
        ----------
        index1 : int
            input port index.
        index2 : int
            output port index.

        Returns
        -------
        pandas.DataFrame
            DataFrame containing frequency, magnitude (dB), and phase (degrees).

        Raises
        ------
        ValueError
            If the simulation type is not driven or if the specified indices are invalid.
        """
    
        if self.config.config["Problem"]["Type"] != "Driven":
            raise ValueError("Simulation type is not Driven, no port S-parameters to extract")
            
        else:
        
            Smatrix_results = self.config.config["Problem"]["Output"]+"/port-S.csv"
            Smatrix = pd.read_csv(Smatrix_results)
            
            ReSij =  '             |S[{}][{}]| (dB)'.format(index1,index2)
            ImSij =  '        arg(S[{}][{}]) (deg.)'.format(index1,index2)
            
            try:
                f_GHz = Smatrix['        f (GHz)'].to_numpy()
                ReSij_column = Smatrix[ReSij].to_numpy()
                ImSij_column = Smatrix[ImSij].to_numpy()
                columns = ["frequency_GHz","|S[{}][{}]| (dB)".format(index1,index2),"arg(S[{}][{}]) (deg)".format(index1,index2)]
                Scustom = pd.Dataframe({columns[0]:f_GHz,columns[1]:ReSij_column,columns[2]:ImSij_column})
                return Scustom
                
            except:
                raise ValueError("Selected S_ij matrix elements do not exist, please check specified indices")
                    

        

    def plot_field(self,
                   field,
                   index,
                   normal="z",
                   origin=(0, 0, 0),
                   quantity="magnitude",
                   part="real",
                   scale=None,
                   cmap=None,
                   show=True,
                   save=None):
        
        """
        Plot a field from Palace simulation output (ParaView/PVD).

        Parameters
        ----------
        field : str
            Field to visualize. Supported options:
            "E" (electric field), "B" (magnetic field),
            "U_e" (electric energy density),
            "U_m" (magnetic energy density),
            "S" (Poynting vector).

        index : int
            Mode index (time step) to visualize.

        normal : str or tuple, optional
            Normal vector defining the slice plane. Default is "z"
            (i.e., an xy-plane slice). Can also be a 3-tuple.

        origin : tuple, optional
            Origin of the slice plane. Default is (0, 0, 0).

        quantity : str, optional
            Quantity to plot for vector fields ("E", "B", "S").
            Options:
            - "magnitude" : ||field||
            - "x", "y", "z" : corresponding Cartesian component

            Ignored for scalar fields ("U_e", "U_m").
            
        part : str, optional
            For vector fields ("E", "B", "S") and when `quantity` is not set to `"magnitude"`
            selects which part of the complex field to visualize:
            
            - "real" : real part (default)
            - "imag" : imaginary part
            
        scale : tuple, optional
            Color scale limits for the plot, given as (vmin, vmax).
            If None (default), limits are set automatically:
            - For "magnitude": based on the 1st–99th percentile range
            - For components: symmetric about zero using the 99th percentile

        cmap : str, optional
            Matplotlib colormap to use for visualization.
            If None (default), uses:
            - "inferno" for magnitude plots
            - "RdBu_r" for component plots (diverging, centered at zero)
            
        show : bool, optional
            If True (default), display the plot.

        save : str or None, optional
            If provided, save the plot to the specified file path
            If None (default), the plot is not saved.

        Notes
        -----
        - Vector fields are reconstructed from real and imaginary components.
        - Eigenmode fields are complex; "magnitude" is phase-independent,
          while individual components depend on the chosen phase convention.
        """
        
        if self.config.config["Problem"]["Type"] == "Electrostatic":
        
            vector_fields = ["E"]
            scalar_fields = ["V","U_e"]
            field_components = {"x":0,"y":1,"z":2}
            
        elif self.config.config["Problem"]["Type"] == "Magnetostatic":
        
            vector_fields = ["B","A"]
            scalar_fields = ["U_m"]
        
        else:
            vector_fields = ["E","B","S"]
            scalar_fields = ["U_e","U_m"]
        
        field_components = {"x":0,"y":1,"z":2}
        
        
        if field not in vector_fields and field not in scalar_fields:
            raise ValueError('Specified field is unknown, available options are "E","B","S","U_e","U_m"')
            
            
        type = self.config.config["Problem"]["Type"].lower()
        paraview_data = self.config.config["Problem"]["Output"] + "/paraview/" + type + "/{}.pvd".format(type)
            
        reader = pv.get_reader(paraview_data)
        reader.set_active_time_point(index)
        mb = reader.read()
        block=mb[0]

        current_slice = block.slice(normal=normal, origin=origin)
    
        if field in vector_fields:
    
            try:
                real = current_slice.point_data["{}_real".format(field)]
                imag = current_slice.point_data["{}_imag".format(field)]
                
                if quantity == "magnitude":
                    F = real + 1j * imag
                    mag = np.linalg.norm(F, axis=1)
                    data = mag
                else:
                    if part == "real":
                        data = real[:,field_components[quantity]]
                    else:
                        data = imag[:,field_components[quantity]]
            
            except:
                F = current_slice.point_data["{}".format(field)]
                if quantity == "magnitude":
                    mag = np.linalg.norm(F, axis=1)
                    data = mag
                else:
                    data = F[:,field_components[quantity]]
            
        else:
            data = current_slice.point_data["{}".format(field)]
            
        points = current_slice.points
        
        if normal == "z":
            x_plot = points[:, 0]
            y_plot = points[:, 1]
        elif normal == "y":
            x_plot = points[:, 0]
            y_plot = points[:, 2]
        elif normal == "x":
            x_plot = points[:, 1]
            y_plot = points[:, 2]
        else:
            raise ValueError("normal must be 'x', 'y', or 'z'")

        # choose colormap
        if cmap is None:
            cmap = "inferno" if quantity == "magnitude" else "RdBu_r"

        # autoscale
        if scale is None:
            if quantity == "magnitude":
                vmin, vmax = np.percentile(data, [1, 99])
            else:
                vmax = np.percentile(np.abs(data), 99)
                vmin = -vmax
        else:
            vmin, vmax = scale

        sc = plt.scatter(x_plot, y_plot, c=data, s=1, cmap=cmap, vmin=vmin, vmax=vmax)
        plt.colorbar(sc)
        
        if show == True:
            plt.show()
        else:
            plt.savefig(save)
            plt.close()
            
        
